//
//  Device.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class Device: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _deviceId: String?
    @objc var _deviceName: String?
    @objc var _deviceStatus: String?
    @objc var _lastUpdated: String?
    
    class func dynamoDBTableName() -> String {

        return "lightblu-mobilehub-144292023-Device"
    }
    
    class func hashKeyAttribute() -> String {

        return "_deviceId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_deviceName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_deviceId" : "deviceId",
               "_deviceName" : "deviceName",
               "_deviceStatus" : "deviceStatus",
               "_lastUpdated" : "lastUpdated",
        ]
    }
}
