//
//  LightOperations.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class LightOperations: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _lightdeviceName: String?
    @objc var _phonedeviceName: String?
    @objc var _colorId: String?
    @objc var _intensityVal: String?
    @objc var _lastUpdated: String?
    @objc var _opId: NSNumber?
    @objc var _deviceStatus: String?
    
    class func dynamoDBTableName() -> String {

        return "lightblu-mobilehub-144292023-LightOperations"
    }
    
    class func hashKeyAttribute() -> String {

        return "_lightdeviceName"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_phonedeviceName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_lightdeviceName" : "LightdeviceName",
               "_phonedeviceName" : "PhonedeviceName",
               "_colorId" : "ColorId",
               "_intensityVal" : "IntensityVal",
               "_lastUpdated" : "LastUpdated",
               "_opId" : "Op_id",
               "_deviceStatus" : "deviceStatus",
        ]
    }
}
