//
//  QRPasswordTable.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class QRPasswordTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _deviceId: String?
    @objc var _lastUpdated: String?
    @objc var _password: String?
    
    class func dynamoDBTableName() -> String {

        return "lightblu-mobilehub-144292023-QRPasswordTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_deviceId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_lastUpdated"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_deviceId" : "DeviceId",
               "_lastUpdated" : "LastUpdated",
               "_password" : "Password",
        ]
    }
}
